#!/usr/bin/env php
<?php

include_once dirname(__FILE__) . "/vendor/autoload.php";
include_once dirname(__FILE__) . "/Apache2.php";

use Diversen\ParseArgv;
use Diversen\Apache2;

$p = new ParseArgv();

$help_message = <<<EOF
apache2-host-enabler

A simple tool for creating, enabling, and disabling apache2 virtual host 

Enable:

    mkdir test.somesite.com

    cd test.somesite.com

    sudo a2host.phar --enable --htdocs=www test.somesite.com

If the flag htdocs is not set then the default htdocs name is `htdocs`

After the host has been enabled you can visit: http://test.somesite.com

Disable:

    cd somesite.com

    sudo a2host.phar --disable somesite.com

This does not delete any files. It just disables the host.

Enable https: 
    
    sudo certbot --apache
EOF;

$error = null;
if (!isset($p->values[0])) {
    $error = true;
} else {
    $hostname = $p->values[0];
}

if (isset($p->flags['enable'])) {
    $command = 'enable';
} else if (isset($p->flags['disable'])) {
    $command = 'disable';    
} else {
    $error = true;
}

$options = [];
if (isset($p->flags['htdocs'])) {
    $options['htdocs'] = $p->flags['htdocs'];
}


if ($error) { 
    print($help_message . "\n");
} else {

    if ($command == 'enable') {
        Apache2::enableSite($hostname, $options);
    }

    if ($command == 'disable') {
        Apache2::disableSite($hostname);
    }
}
